### PR TITLE
Make countingsort.c3's recursion stage branchless

### PR DESCRIPTION
**Pull request by Andersama**
Tracks the three potential cases for each fallback, item counts ranging from [2,32], [33,128], [128, ...] and uses a loop specifically for each fallback.

### CODE REVIEW

**Comment by lerno** [comment]
Do you still want to add this?

**Comment by Andersama** [comment]
Yeah, this one is worth doing.

**Comment by lerno** [comment]
It says "draft". Does it mean it's not ready to be merged?

**Comment by Andersama** [comment]
Oh, that's what you meant.

**Comment by lerno** [comment]
Thank you!

**Pull request merged**
