### PR TITLE
Mention LLVM 16 in the README [skip ci]

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by lerno** [comment]
LLVM 16 is still broken :(

**Comment by data-man** [comment]
Yes.
In my PC `libmlir*` also conflicts with 'libmlir*-16-*', so I uninstall them.

**Comment by lerno** [comment]
I'm not sure libmlir is even needed? You can try removing it.

**Comment by lerno** [comment]
BTW there was a patch about 8 days ago that I was waiting for that people thought fixed the issue, but apparently not. And now there's another patch which is hopefully being added soon (it's approved at least). I've been nagging people about it on the LLVM discord 😄

**Comment by data-man** [comment]
> I'm not sure libmlir is even needed? You can try removing it.

With installed `mlir-16-tools` and uninstalled `libmlir-16-dev` I got this:
```
CMake Error at /usr/lib/llvm-16/lib/cmake/llvm/LLVMExports.cmake:1640 (message):
  The imported target "MLIRSupportIndentedOstream" references the file

     "/usr/lib/llvm-16/lib/libMLIRSupportIndentedOstream.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/llvm-16/lib/cmake/llvm/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/llvm-16/cmake/LLVMConfig.cmake:329 (include)
  CMakeLists.txt:72 (find_package)
```

**Comment by lerno** [comment]
Maybe one should just do something different to detect where the LLVM libraries are. This just feels broken.

**Comment by data-man** [comment]
`$ apt-cache rdepends libllvm15`

```
libllvm15
Reverse Depends:
  clang-format-15
  mlir-15-tools
  llvm-15-tools
  llvm-15-runtime
  llvm-15-linker-tools
  llvm-15-dev
  llvm-15
  lld-15
  liblldb-15
  liblld-15
  libclang1-15
  libclang-cpp15
  libclang-common-15-dev
  clangd-15
  clang-tools-15
  clang-tidy-15
  clang-format-15
  clang-15
  mlir-15-tools
  llvm-15-tools
  llvm-15-runtime
  llvm-15-linker-tools
  llvm-15-dev
  llvm-15
  lldb-15
  lld-15
  libomp5-15
  libomp-15-dev
  libmlir-15
  libllvm15-dbgsym
  liblldb-15
  liblld-15
  libclang1-15
  libclang-cpp15
  libclang-common-15-dev
  clangd-15
  clang-tools-15
  clang-tidy-15
  clang-format-15
  clang-15
  mlir-15-tools
  llvm-15-tools
  llvm-15-runtime
  llvm-15-linker-tools
  llvm-15-dev
  llvm-15
  lldb-15
  lld-15
  libomp-15-dev
  libmlir-15
  liblldb-15
  liblld-15
  libclang1-15
  libclang-cpp15
  libclang-common-15-dev
  clangd-15
  clang-tools-15
  clang-tidy-15
  clang-15
```

**Comment by lerno** [comment]
You probably get more than you need. I don't see why clang nor mlir should be needed.

**Comment by lerno** [comment]
LLVM 16 works again now :D

**Pull request merged**
