### PR TITLE
Support build with mimalloc

### PR DESCRIPTION
**Pull request by data-man**
Sources taken from [dev](https://github.com/microsoft/mimalloc/tree/dev) branch.

### CODE REVIEW

**Comment by lerno** [comment]
What is the point of adding mimalloc?

**Comment by data-man** [comment]
It's really fast. :)
And I think it can be used as replacement for `std.mem._malloc` in the future.

**Comment by lerno** [comment]
Currently the compiler doesn't really use malloc.

**Comment by data-man** [comment]
Using https://github.com/nordlow/compiler-benchmark
`$ ./benchmark --languages c3`
With mimalloc:
| Lang-uage | Temp-lated | Check Time [us/fn] | Compile Time [us/fn] | Build Time [us/fn] | Run Time [us/fn] | Check RSS [kB/fn] | Build RSS [kB/fn] | Exec Version | Exec Path |
| :-------: | ---------- | :----------------: | :------------------: | :----------------: | :--------------: | :---------------: | :---------------: | :----------: | :-------: |
| C3        | No         | N/A                | N/A                  |  494.3 (best)      |    608 (best)    | N/A               |   21.1 (best)     | unknown      | c3c       |

Without mimalloc:
| Lang-uage | Temp-lated | Check Time [us/fn] | Compile Time [us/fn] | Build Time [us/fn] | Run Time [us/fn] | Check RSS [kB/fn] | Build RSS [kB/fn] | Exec Version | Exec Path |
| :-------: | ---------- | :----------------: | :------------------: | :----------------: | :--------------: | :---------------: | :---------------: | :----------: | :-------: |
| C3        | No         | N/A                | N/A                  |  566.2 (best)      |    586 (best)    | N/A               |   15.4 (best)     | unknown      | c3c       |

**Comment by lerno** [comment]
Please pull the latest C3 and take the benchmark from here: https://github.com/lerno/compiler-benchmark

**Comment by data-man** [comment]
`$ ./benchmark --languages c3 --function-count 200 --function-depth 200 --run-count 5`

With mimalloc:
- Check took 0.175 seconds (using "/usr/local/sbin/c3c" version PRE.6)
- Compile took 2.724 seconds (using "/usr/local/sbin/c3c" version PRE.6)
- Build took 2.874 seconds (using "/usr/local/sbin/c3c" version PRE.6)

| Lang-uage | Temp-lated | Check Time [us/fn] | Compile Time [us/fn] | Build Time [us/fn] | Run Time [us/fn] | Check RSS [kB/fn] | Build RSS [kB/fn] | Exec Version | Exec Path |
| :-------: | ---------- | :----------------: | :------------------: | :----------------: | :--------------: | :---------------: | :---------------: | :----------: | :-------: |
| C3        | No         |    4.4 (best)      |   67.4 (best)        |   71.6 (best)      |    155 (best)    |    5.0 (best)     |    7.7 (best)     | PRE.6        | c3c       |

Without mimalloc:
- Check took 0.175 seconds (using "/usr/local/sbin/c3c" version PRE.6)
- Compile took 2.854 seconds (using "/usr/local/sbin/c3c" version PRE.6)
- Build took 3.025 seconds (using "/usr/local/sbin/c3c" version PRE.6)

| Lang-uage | Temp-lated | Check Time [us/fn] | Compile Time [us/fn] | Build Time [us/fn] | Run Time [us/fn] | Check RSS [kB/fn] | Build RSS [kB/fn] | Exec Version | Exec Path |
| :-------: | ---------- | :----------------: | :------------------: | :----------------: | :--------------: | :---------------: | :---------------: | :----------: | :-------: |
| C3        | No         |    4.4 (best)      |   71.6 (best)        |   75.7 (best)      |    242 (best)    |    5.1 (best)     |    7.1 (best)     | PRE.6        | c3c       |

**Comment by data-man** [comment]
With `--function-count 500` I got `FATAL ERROR Symtab exceeded capacity, please increase --symtab. -> in symtab_add @ in /home/dataman/Projects/C3/c3c/src/compiler/symtab.c:232`

**Comment by lerno** [comment]
Yeah, either set it higher or adjust the max functions.

**Comment by lerno** [comment]
I just can't see how this could work unless you're getting LLVM to use mimalloc?

**Comment by data-man** [comment]
I'm linking with `mimalloc-static` and mimalloc's option `MI_OVERRIDE` == `ON` by default.

**Comment by lerno** [comment]
The thing is that LLVM should be using a slab allocator anyway, so the performance here is surprising to say the least. As you see you're not getting any improvements in the compiler itself (the "check") part, but rather it's LLVM which is accelerated by this.

**Comment by lerno** [comment]
Can we make mimalloc just a build option without pulling the entire mimalloc as a dependency?

**Comment by data-man** [comment]
As a user-installed dependency?
Of course.

**Comment by lerno** [comment]
Yes, so that while it's convenient to add mimalloc (and possibly it will load itself if cmake finds it), it's not part of the c3c source tree.

**Comment by data-man** [comment]
Well, then I see three options:

- using system's mimalloc if it's installed. Or
- download mimalloc's source using CMake's `FetchContent*`. And/or
- add `MIMALLOC_DIR` option to CMakeLists

**Comment by lerno** [comment]
Doesn't the first option sound good? "If it's installed use it"

**Comment by lerno** [comment]
Also an option to download mimalloc would be nice.

**Comment by data-man** [comment]
I also think so.
But which version: latest tagged release or latest committed?

**Comment by lerno** [comment]
I think the last tagged release would be best.

**Comment by lerno** [comment]
BTW do you see any changes to the benchmark results with the latest version?

**Comment by data-man** [comment]
Yes, the results are much better. Thanks!
```$ ./benchmark --langs c3 --function-count 200 --function-depth 200 --run-count 10```
Without mimalloc:
- Check took 0.124 seconds (using "/usr/local/bin/c3c" version PRE.10)
- Compile took 2.503 seconds (using "/usr/local/bin/c3c" version PRE.10)
- Build took 2.668 seconds (using "/usr/local/bin/c3c" version PRE.10)

| Lang-uage | Temp-lated | Check Time [us/fn] | Compile Time [us/fn] | Build Time [us/fn] | Run Time [us/fn] | Check RSS [kB/fn] | Build RSS [kB/fn] | Exec Version | Exec Path |
| :-------: | ---------- | :----------------: | :------------------: | :----------------: | :--------------: | :---------------: | :---------------: | :----------: | :-------: |
| C3        | No         |    3.1 (best)      |   62.6 (best)        |   66.7 (best)      |    162 (best)    |    4.5 (best)     |    5.9 (best)     | PRE.10       | c3c       |

With mimalloc:
- Check took 0.129 seconds (using "/usr/local/bin/c3c" version PRE.10)
- Compile took 2.381 seconds (using "/usr/local/bin/c3c" version PRE.10)
- Build took 2.543 seconds (using "/usr/local/bin/c3c" version PRE.10)

| Lang-uage | Temp-lated | Check Time [us/fn] | Compile Time [us/fn] | Build Time [us/fn] | Run Time [us/fn] | Check RSS [kB/fn] | Build RSS [kB/fn] | Exec Version | Exec Path |
| :-------: | ---------- | :----------------: | :------------------: | :----------------: | :--------------: | :---------------: | :---------------: | :----------: | :-------: |
| C3        | No         |    3.2 (best)      |   59.5 (best)        |   63.6 (best)      |    163 (best)    |    4.6 (best)     |    6.4 (best)     | PRE.10       | c3c       |

So maybe this PR can be closed, if you wish. :smile:

**Comment by lerno** [comment]
I think the speedup with mimalloc is worth including though.

**Comment by data-man** [comment]
I'll test this option in CI in another PR.

**Comment by lerno** [comment]
Thank you.

**Comment by data-man** [comment]
Thanks!
Note: an user can set the used version of mimalloc.
I'm using `cmake -DC3_MIMALLOC_TAG=dev` :smile:

**Comment by lerno** [comment]
I'm actually having issues now, with mimalloc throwing asserts when LLVM uses it.

**Pull request merged**
