### PR TITLE
Add methodsof to type info

### PR DESCRIPTION
**Pull request by Dodzey**
Adding draft pull request to get feedback on implementation, and discuss.
This is a useful feature, similar to `membersof` but returns the names of methods associated with the type.
Has previously been discussed on discord.

Usage:
```
$foreach ($mm : $Type.methodsof)
   $echo $mm;
$endforeach
```

### CODE REVIEW

**Comment by data-man** [comment]
There are no tests. Does this support interfaces?

**Comment by lerno** [comment]
I think `methodsof` could probably just return the names, this prevents the proliferation of compile time types. Because you can then get the actual function like this: 

```c
$foreach ($name : $Type.methodsof)
   $echo $name;
   // Let's grab the function pointer!
   void* func_ref = &$Type.$eval($name);   
$endforeach
```

**Comment by lerno** [comment]
Look at test/unit/regression, you can add it there in the same manner. Use "assert" to test the expected results.

**Comment by lerno** [comment]
CONST_METHOD should not be needed now I think.

**Comment by lerno** [comment]
One final thing: it needs to be mentioned in the release notes. Can you add a line under 0.6.2?

**Comment by lerno** [comment]
Thank you!

**Pull request merged**
