### PR TITLE
Add variants of `DString.insert_at` to match `.append`

### PR DESCRIPTION
**Pull request by chri-k**
Adds more methods to insert things in the middle of a DString:
```
insert_string_at(usz, DString)
insert_char_at(usz, char)
insert_char32_at(usz, Char32)
insert_utf32_at(usz, Char32[])
```
And to match `.append`, i renamed `.insert_at(usz, String)` to `insert_chars_at`, and instead made `.insert_at` a macro that picks a function based on type, like `.append` (it will pick the renamed one for `String` so nothing should break).

I also updated `append_utf32` and `append_char32`  to now return the size of the utf8 they appended for convenience (and of course the insert versions do the same). That shouldn't affect anything either

### CODE REVIEW

**Comment by chri-k** [comment]
And of course i somehow managed to include six lines of space indentation in the PR, despite already having undone the commit once to fix those exact same six lines of space indentation.

**Comment by lerno** [comment]
Can you add something in releasenotes about this as well please?

**Comment by chri-k** [comment]
My bad. Added line to release notes (and fixed the spaces)

**Comment by lerno** [comment]
Thank you!

**Pull request merged**
