### PR TITLE
Json AST: Adding 'constants' and Improving 'globals' #1540, #1541

### PR DESCRIPTION
**Pull request by cardisk**
Adding constants and improving globals inside the Json AST with information about types and values.

### CODE REVIEW

**Comment by cardisk** [comment]
I fixed the problem that CI reported. I was not aware of the size difference of uint64_t on different operating systems.

**Comment by lerno** [comment]
You mean size of long?

**Comment by cardisk** [comment]
Yesterday I roughly fixed the printf problem. The first time, CI failed on linux distros because of the wrong format used (%lld) for uint64_t. I never worked with 64 bits wide types and I was short on free time so I changed the code adding a check on the operating system.
Today, after a bit more research, I found PRIu64 macro to print this type. Is it better to use such macro, or should I leave it like it is now?

**Comment by lerno** [comment]
I think the simplest thing is simply to cast the value to unsigned long long before passing it to printf, and using "%llu"

**Comment by cardisk** [comment]
I've done the change, now it should be ok

**Comment by lerno** [comment]
While I'm not sure it's right to have the expressions in the AST, let's try it out. Thank you for doing this.

**Pull request merged**
