### PR TITLE
Add `format` field to `Formatter` struct.

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by lerno** [comment]
What is the point of this?

**Comment by data-man** [comment]
An user-defined formatters can support a non-standard syntax.

**Comment by lerno** [comment]
format[] is the whole formatting string. So "%s foo %z". Anyone doing output with custom formatting does not know if "%s" or "%z" is the formatting string. In addition the registered function will only be invoked on %s.

**Comment by lerno** [comment]
So is it ok to close this one? I think being able to inject additional formatting types is fundamentally a good idea, but it needs more than access to `format`.

**Comment by data-man** [comment]
> format[] is the whole formatting string.

Yes, it will allow a custom parsing.

**Comment by lerno** [comment]
No it doesn't. Let's say you have the following: `io::printf("%s %s %d", a, a, a)`. What happens here is that if you registered a type Foo with a formatting function, it will first give a callback with the formatting string set to `"%s %s %d"`, then there will be another callback with `"%s %s %d"` again. The formatting function is never invoked on %d.

So:
1. There is no way for the formatting function to know what formatting location it is in given just the formatting string.
2. Only %s ever invokes formatting functions, so no custom formatters like using "%m" to grab the month for a "Time" type will ever work.

My point is therefore that to support custom formatting %<some letter> hooks would be required. If additional formatting hints should be passed to the formatting function, this information needs to be preparsed or at a minimum the actual formatting substring is passed (e.g. "%s")

**Pull request closed without merging**
