### PR TITLE
Add inlined `memcpy` and `memset` builtins and macros.

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by data-man** [comment]
For some reason `$$memset_inline` IR isn't correct for LLVM < 15. :(

**Comment by data-man** [comment]
@lerno Maybe remove LLVM IR from `test/test_suite|suite2/stdlib/map.c3t`?

**Comment by lerno** [comment]
Eventually.

**Comment by lerno** [comment]
The reason this is not passing in those tests is probably because some functions in mem moved, which meant the panic function call got a different line number. Try checking what the line should be and update that particular value in the expected IR

**Comment by lerno** [comment]
Thank you

**Pull request merged**
