### PR TITLE
Add `$$reverse` built-in.

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by lerno** [comment]
I'd like to avoid adding experimental llvm features yet.

**Comment by data-man** [comment]
But why? The `vector.reverse` exists in versions 13-16 and works fine.

If experimental functions are not used in **real** compilers, they will be still experimental for a long time. :)

**Comment by lerno** [comment]
It seems like the tests are failing as well?

**Comment by data-man** [comment]
>llvm_codegen_expr.c:4421:22: error: 'BUILTIN_REVERSE' undeclared (first use in this function); did you mean 'BUILTIN_BITREVERSE'?

It's mystical, everything compiles on my PC without errors. :(

**Comment by data-man** [comment]
Test:
```rust
import std::io;

fn void main()
{
    io::printfln("LLVM version = %s", $$LLVM_VERSION);

    ushort u1 = 1;
    ushort u2 = 2;

    long i1 = 1;
    long i2 = 2;

    short[<2>] vu1 = { u1, u2 };
    long[<2>] vi1 = { i1, i2 };

    float[<2>] vf1 = { u1, u2 };

    short[<2>] vu2 = reverse(vu1);
    long[<2>] vi2 = reverse(vi1);
    float[<2>] vf2 = reverse(vf1);

    io::printfln("u1 = %s", u1);
    io::printfln("u2 = %s", u2);

    io::printfln("i1 = %s", i1);
    io::printfln("i2 = %s", i2);

    io::printfln("vu1 = %s", vu1);
    io::printfln("vi1 = %s", vi1);
    io::printfln("vf1 = %s", vf1);
    io::printfln("vu2 = %s", vu2);
    io::printfln("vi2 = %s", vi2);
    io::printfln("vf2 = %s", vf2);

}
```

Results:
```
LLVM version = 12
u1 = 1
u2 = 2
i1 = 1
i2 = 2
vu1 = [<1, 2>]
vi1 = [<1, 2>]
vf1 = [<1.000000, 2.000000>]
vu2 = [<2, 1>]
vi2 = [<2, 1>]
vf2 = [<2.000000, 1.000000>]
```

**Comment by lerno** [comment]
I added reverse based on shufflevector, which was the recommended solution.

**Comment by data-man** [comment]
Thank you.
I have already tested it and the asm's output is identical to `llvm.experimental.vector.reverse`.

**Pull request closed without merging**
