### PR TITLE
std/collections: use List.remove_if and List.remove_using_test for Li…

### PR DESCRIPTION
**Pull request by pierrec**
…st.remove and List.compact

### CODE REVIEW

**Comment by lerno** [comment]
This would create another function call for every element checked though?

**Comment by pierrec** [comment]
Good point. Adding @inline to the lambda should work, right?

> return self.remove_if(fn bool(p) @inline => *p == null);

**Comment by lerno** [comment]
Can you benchmark using various ways including the first?Sent from my iPhone1 sep. 2023 kl. 18:58 skrev Pierre Curto ***@***.***>:﻿
Good point. Adding @inline to the lambda should work, right?

return self.remove_if(fn bool(p) @inline => *p == null);

**Comment by pierrec** [comment]
```
module bench;
import std::collections::list;

def PtrList = List(<void*>);

fn void main()
{
	const N = 40_000;
	PtrList test;
	for (usz i = 0; i < N; i++)
	{
		test.add_array({ null, &test });
		test.compact();
	}
}
```

Initial method:
./bench  0.63s user 0.01s system 98% cpu 0.648 total

Proposed one:
./bench  3.49s user 0.02s system 99% cpu 3.523 total

So... forget this PR!

**Comment by lerno** [comment]
That seems surprisingly big a difference. Is this really -O3 --fast?

**Pull request closed without merging**
