### PR TITLE
Add `$$muladd` built-in.

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by lerno** [comment]
What is the advantage over fma?

**Comment by data-man** [comment]
> If a fused multiply-add is required, the corresponding [llvm.fma](https://llvm.org/docs/LangRef.html#int-fma) intrinsic function should be used instead.

**Comment by data-man** [comment]
```rust
fn void main()
{
    double a = 1.0;
    double b = 2.0;
    double c = 3.0;
    double f = $$fma(a, b, c);
}
```

```rust
fn void main()
{
    double a = 1.0;
    double b = 2.0;
    double c = 3.0;
    double m = $$muladd(a, b, c);
}
```

```asm
fma_main:                               # @fma_main
# %bb.0:                                # %entry
        subq    $40, %rsp
        movsd   .LCPI0_2(%rip), %xmm0           # xmm0 = mem[0],zero
        movsd   %xmm0, 32(%rsp)
        movsd   .LCPI0_1(%rip), %xmm0           # xmm0 = mem[0],zero
        movsd   %xmm0, 24(%rsp)
        movsd   .LCPI0_0(%rip), %xmm0           # xmm0 = mem[0],zero
        movsd   %xmm0, 16(%rsp)
        movsd   32(%rsp), %xmm0                 # xmm0 = mem[0],zero
        movsd   24(%rsp), %xmm1                 # xmm1 = mem[0],zero
        movsd   16(%rsp), %xmm2                 # xmm2 = mem[0],zero
        callq   fma@PLT
        movsd   %xmm0, 8(%rsp)
        addq    $40, %rsp
        retq
```

```asm
muladd_main:                            # @muladd_main
# %bb.0:                                # %entry
        movsd   .LCPI0_2(%rip), %xmm0           # xmm0 = mem[0],zero
        movsd   %xmm0, -8(%rsp)
        movsd   .LCPI0_1(%rip), %xmm0           # xmm0 = mem[0],zero
        movsd   %xmm0, -16(%rsp)
        movsd   .LCPI0_0(%rip), %xmm0           # xmm0 = mem[0],zero
        movsd   %xmm0, -24(%rsp)
        movsd   -8(%rsp), %xmm0                 # xmm0 = mem[0],zero
        movsd   -16(%rsp), %xmm2                # xmm2 = mem[0],zero
        movsd   -24(%rsp), %xmm1                # xmm1 = mem[0],zero
        mulsd   %xmm2, %xmm0
        addsd   %xmm1, %xmm0
        movsd   %xmm0, -32(%rsp)
        retq
```

**Comment by lerno** [comment]
Since this seems to be float/double only, perhaps we should just do the optimization on every (a + b)*c with floats? This is what clang does.

**Comment by data-man** [comment]
Probably, but for what optimization level? O1, O2? IDK.

**Comment by lerno** [comment]
It's simple to do in the lowering itself (which seems to be what Clang does)

**Comment by data-man** [comment]
Old school programmers prefer manual optimizations. :)

**Comment by lerno** [comment]
I've made a possible patch that just does (a*b) +c => muladd

**Comment by data-man** [comment]
I saw `dev` branch. Thanks! :)

**Comment by lerno** [comment]
Yeah, I wanted to add those further changes.

**Pull request closed without merging**
