### PR TITLE
Fix formatter dereferencing null ZString, print "(null)" for null pointers.

### PR DESCRIPTION
**Pull request by cbuttner**
Closer to printf-like behavior.

### CODE REVIEW

**Comment by lerno** [comment]
Can I ask for a unit test too? I think we might detect other regressions too if we have that.

**Comment by lerno** [comment]
I'll accept this and I add the test and release notes for it, but try to add that next time.

**Comment by cbuttner** [comment]
Thanks, will keep in mind, although you could've just waited until I got around to it.

**Comment by lerno** [comment]
Hot on the trigger you know 😄. I feel bad when pull requests aren't merged quickly.

**Pull request merged**
