### PR TITLE
Update build-with-docker.sh

### PR DESCRIPTION
**Pull request by data-man**
I don't use Docker, but I hope these are valid changes.

### CODE REVIEW

**Comment by lerno** [comment]
Can we have some confirmation that this works? I don't have a setup to test it.

**Comment by data-man** [comment]
cc @gdm85 :)

**Comment by gdm85** [comment]
I don't think it's a good idea to remove Ubuntu 18, see how far in the future it is supported here: https://ubuntu.com/about/release-cycle

Cutting out an LTS release (and all the people using it) to save a couple lines here does not seem a worthy gain; I also think the `DEPS` approach was more flexible but that's less important.

I verified that this version still works but you need to remove `lib` from the `rm -rf` line (and the corresponding `mv` on the last line in the script) otherwise it will fail:
```
CMake Error at CMakeLists.txt:84 (file):
  file COPY cannot find "/home/c3c/source/lib": No such file or directory.
```

I guess at some point `lib` was versioned so this script should not touch it anymore.

**Comment by data-man** [comment]
> I don't think it's a good idea to remove Ubuntu 18

According to [https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=llvm](https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=llvm) Bionic hasn't LLVM 12.

In any case, `build-with-docker.sh` is incorrect because the minimum required LLVM version must be >= 12 now.

**Comment by data-man** [comment]
> I verified that this version still works but you need to remove lib from the rm -rf line (and the corresponding mv on the last line in the script) otherwise it will fail:

Thank you! Fixed.

**Comment by gdm85** [comment]
I wasn't aware that LLVM12 has become a minimum requirement, in that case no point keeping Ubuntu18.

The last command `mv c3c ../bin/ && mv lib ../bin/"` could be compacted as `mv c3c lib ../bin/`.

**Comment by lerno** [comment]
Anything else to update here? Or is it ready to add? @gdm85

**Comment by gdm85** [comment]
@lerno yes it's fine, it works.

I will submit a PR to add `podman` support after you merge this one.

**Comment by gdm85** [comment]
There it is: https://github.com/c3lang/c3c/pull/418

I/you can rebase it after this is merged.

**Comment by lerno** [comment]
Thank you

**Pull request merged**
