### PR TITLE
Disable mimalloc by the option

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by lerno** [comment]
Do you see any issues running LLVM 13 with mimalloc on debug?

**Comment by data-man** [comment]
I'm using LLVM 14 and mimalloc-dev. No issues. :)
Is there an issue with a specific file?

**Comment by lerno** [comment]
Usually it breaks on `LLVMGetTargetMachineTriple(machine)`

**Comment by data-man** [comment]
Can you try this:
```sh
!/bin/sh
mkdir -p build-rel
cd build-rel
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DC3_MIMALLOC_TAG=dev -DC3_USE_MIMALLOC=ON ../ "$@"
```

**Comment by data-man** [comment]
And yes, what OS are you using?

**Comment by lerno** [comment]
Mac, I think a good idea would be to disable on Mac and Win32 then? I have checked and it fails to intercept calls to asprintf. Presumably something similar that happens to LLVM.

**Comment by data-man** [comment]
Mac should be in CI! :)

**Comment by lerno** [comment]
I would be grateful for contributions enabling mac CI (and MSVC!)

**Pull request merged**
