### PR TITLE
make io.Stream read_byte use read if possible

### PR DESCRIPTION
**Pull request by pierrec**

### CODE REVIEW

**Comment by lerno** [comment]
I am making the overall changes to stream now, so this change will likely conflict with that one. Let's look at this one later.

**Comment by lerno** [comment]
Dot should be "precision", right? That's how it works for regular printf I think it's just that "precision" in the string case means string length.

**Comment by pierrec** [comment]
> Dot should be "precision", right? That's how it works for regular printf I think it's just that "precision" in the string case means string length.

oh yes...

**Comment by lerno** [comment]
Thanks for fixing this.

**Pull request merged**
