### PR TITLE
Add initial FreeBSD support

### PR DESCRIPTION
**Pull request by wilsonk**
This seems to build the compiler on FreeBSD fine. Then all of the regression tests pass for the unit tests, and most of the stdlib tests pass, with a few errors. It is a start, at least. 

Not tested on Net/Open BSD's at this point. The demo1 and diagnostic testfragments seemed to need a change also...not sure if this is FreeBSD specific or not?

### CODE REVIEW

**Comment by lerno** [comment]
Rather than having the `BSDS` const in fileinfo, move it to env.c3 and add a `const bool BSD_FAMILY` in the same way, which then can be used like `env::BSD_FAMILY`

**Comment by lerno** [comment]
And was dirent wrong? I think I checked against the netbsd and openbsd headers?

**Comment by wilsonk** [comment]
Ok, I made the changes for the BSD_FAMILY in env.c3 (only saw the os/env.c3 and not that second file in core...duh). Makes more sense now.

I have updated the dirent struct to the most current versions of each BSD. I think I was looking at an older github version before from a third party...but this should be correct now. It may be different for older versions of the BSD's, but I assume we would want to target the newest version unless someone needs older compatibility.

**Comment by lerno** [comment]
Thank you!

**Pull request merged**
