### PR TITLE
lib::std::encoding: add varint::{read,write}

### PR DESCRIPTION
**Pull request by pierrec**

### CODE REVIEW

**Comment by data-man** [comment]
Which varint? :)

https://github.com/mattsta/varint

**Comment by pierrec** [comment]
Ah. I was only aware of [Go's](https://pkg.go.dev/encoding/binary@go1.21.1#ReadUvarint).

**Comment by lerno** [comment]
Perhaps better with `read_network_int($Type, char bytes)` and corresponding write methods. What they will do is then to use the corresponding amount of bytes to read/write the integer.

This often done in protocols, like:
```c
uint elements = foo.read_network_int(uint, 3);
List(<Blurb>) list;
for (uint i = 0; i < elements; i++)
{
   list.push(blurb_read(foo));
}
```

...
```c
bar.write_network_int(list.len(), 3);
foreach (&blurb : list)
{
  blurb_write(foo, blurb);
}
```

**Comment by lerno** [comment]
Oh, I see, but still you might want to make stream methods for it simply?

**Comment by data-man** [comment]
I think `std::serialization` is the best way.

**Comment by pierrec** [comment]
@lerno gentle ping.

**Comment by lerno** [comment]
Thank you!

**Pull request merged**
