### PR TITLE
Fix Segfault and UX of the `c3c project add-target` subcommand

### PR DESCRIPTION
**Pull request by rexim**
My version:

```console
c3c --version
C3 Compiler Version:       0.6.6 (Pre-release, Dec 28 2024 03:58:06)
Installed directory:       /home/rexim/opt/c3/bin/
Git Hash:                  291b26f2300dfaaf8d6c3d8890a3c1294cd39cde
Backends:                  LLVM
LLVM version:              18.1.8
LLVM default target:       x86_64-unknown-linux-gnu
```

Consider the following workflow in a completely empty folder:

```console
$ cat > main.c3 <<END
import std::io;

fn void main() {
    io::printfn("Hello, World");
}
END
$ c3c project add-target main executable
Could not open file "project.json".

$ touch project.json
$ c3c project add-target main executable
Expected a map of project information in 'project.json'.

$ echo {} > project.json
$ c3c project add-target main executable
Segmentation fault
$ Uhm... EXCUSE ME?!!
```

First of all, we have an obvious NULL-dereferencing bug. But that's not the biggest problem. The whole process is absolutely and needlessly excruciating. Why do I have to create the file myself? Why do I have to initialize it? Why add-target can't just do what I mean and create everything for me?

In this patch we

- Fix segfault on `project.json` containing empty map `{}`
- Enable `add-target` to operate on non-existing project files
- Extend `add-target` syntax to accept source through CLI args

So the whole workflow turns into

```console
$ cat > main.c3 <<END
import std::io;

fn void main() {
    io::printfn("Hello, World");
}
END
$ c3c project add-target main executable main.c3
$ cat project.json
{
  "targets": {
    "main": {
      "type": "executable",
      "sources":  [ "main.c3" ]
    }
  }
}
$ c3c run
Hello, World
```

Bam! Very smooth, feels great! Minimum changes required. Please let me know if you see any problems with this patch.

### CODE REVIEW

**Comment by lerno** [comment]
So kind of for people who don't want to use `c3c init <project-name>`? 🤔 I never thought of the project update to work as a custom project init, but if you're finding this work flow then others will as well 😄

**Comment by rexim** [comment]
> So kind of for people who don't want to use `c3c init <project-name>`? 🤔 I never thought of the project update to work as a custom project init, but if you're finding this work flow then others will as well 😄

Yeah, I'm really sorry. I personally find `c3c init` output too overwhelming. I'd prefer to increase the complexity gradually as needed. :D

**Comment by lerno** [comment]
Only one thing: the rest of the code uses Allman brace style, so could you fix your additions to be consistent with that? 🙏

**Comment by lerno** [comment]
> Yeah, I'm really sorry. I personally find c3c init output too overwhelming. I'd prefer to increase the complexity gradually as needed. :D

No it's interesting! This is evolving the product to fit different styles, and that is a good thing.

**Comment by rexim** [comment]
> Only one thing: the rest of the code uses Allman brace style, so could you fix your additions to be consistent with that? 🙏

Done

**Comment by lerno** [comment]
NICE Thank you!

**Pull request merged**
