### PR TITLE
chore: Remove overrides for C3 files (requires github-linguist/linguist#7037)

### PR DESCRIPTION
**Pull request by Real-Packet**

### CODE REVIEW

**Comment by lerno** [comment]
Thank you.

**Comment by Real-Packet** [comment]
I mean, I intended for it to be merged when github-linguist/linguist#7037 is merged, but okay.

**Comment by Caleb-o** [comment]
You can set your PRs to draft if you want a PR, but don't want action yet.

**Comment by Real-Packet** [comment]
I should've but it doesn't matter that much.

**Pull request merged**
