### PR TITLE
sort: add is_sorted

### PR DESCRIPTION
**Pull request by konimarti**
Add `is_sorted` function to check whether a list is sorted or not. Sort order (ascending or descending) will be detected by looking at the data. Add tests.

### CODE REVIEW

**Comment by lerno** [comment]
I can accept this as-is, but note that if you want a generic function you can also implement it as a lambda inside of a macro.

**Comment by lerno** [comment]
If you have this:
```c
macro bool is_sorted(list, cmp = EMPTY_MACRO_SLOT, context = EMPTY_MACRO_SLOT) @builtin
 {
  usz len = sort::@len_from_list(list);
  if (len <= 1) return true;
   return sorted::is_sorted(<$typeof(list), $typeof(cmp), $typeof(context)>)(list, 0, (isz)len - 1, cmp, context);
 }
 ```
 You can use a lambda:
 ```c
 macro bool is_sorted(list, cmp = EMPTY_MACRO_SLOT, context = EMPTY_MACRO_SLOT) @builtin
 {
  var $Type = $typeof(list);
  usz len = sort::@len_from_list(list);
  if (len <= 1) return true;
  var sort = fn bool($Type list, usz start, usz end, $typeof(cmp) cmp, $typeof(context) context) 
  {
 	   ... inline the generic function here ...
  };
  return sort(list, 0, len - 1, cmp, context);
 }
 ```
 Or do you envision people using the generic is_sorted outside of the macro?

**Comment by konimarti** [comment]
Ah, I see. That makes sense, too.

I copied the structure over from the quicksort implementation and figured that the macro is a convenient function for most users but that they can have direct access to the generic is_sorted if need (e.g. when they want to check if only a subsection of the list is sorted, but not sure how relevant that is).

Also, I forgot to add a release note..

**Comment by lerno** [comment]
You could also pull it into a second macro that holds the lambda alone.

**Comment by lerno** [comment]
Thank you!

**Pull request merged**
