### PR TITLE
Adding trigonometric and hyperbolic trigonometric tests 

### PR DESCRIPTION
**Pull request by MendocinoWhiteDeer**
Changes were primarily made to the math_tests module. The main goal is to add tests to test/unit/stdlib/math/math.c3.

Rewrote the test_atan() function to be a bit more compact and organized while adding to the net number of assertions overall. 

Next, I added a number of trigonometric and hyperbolic trigonometric tests. I didn't write tests for sinh, cosh, and tanh because the macros use the exponential macro and not LLVM intrinsics (for now). However, there are inverse hyperbolic trig tests.

When setting up the cosine test I found and fixed a bug where the cosine macro wouldn't accept an integer input.

### CODE REVIEW

**Comment by MendocinoWhiteDeer** [comment]
I'm sorry for all the force pushes. I rewrote all the commits after accidentally adding a binary file and then had to rebase to fix commit typos. As of now, I won't make any further edits on my own.

**Comment by lerno** [comment]
The tests seem to fail on some platforms, I am guessing they're not identical but just less than an epsilon apart?

**Comment by MendocinoWhiteDeer** [comment]
Yeah that seems to be the problem. Direct comparison worked fine on my Linux distribution but it was naive of me to assume checking floats exactly would work cross-platform for so many tests. I could add two macros for floating point comparison into the math module and check for an acceptable tolerance in the test file. I was looking at some of my older C code and I think I could translate it into something like this

```
<*
 @require values::@is_int(x) || values::@is_float(x) "Expected an integer or floating point value"
 @require values::@is_int(y) || values::@is_float(y) "Expected an integer or floating point value"
*>
macro is_approx(x, y, eps)
{
	$if x == y:
	    return true;
	$endif
	$if is_nan(x) || is_nan(y):
	    return false;
	$endif
	return abs(x-y) <= eps; 
}

<*
 @require values::@is_int(x) || values::@is_float(x) "Expected an integer or floating point value"
 @require values::@is_int(y) || values::@is_float(y) "Expected an integer or floating point value"
*>
macro is_approx_rel(x, y, eps)
{
	$if x == y:
	    return true;
	$endif
	$if is_nan(x) || is_nan(y):
	    return false;
	$endif
	return abs(x-y) <= eps * max(abs(x), abs(y)); 
}
```

The first one is for comparing small values near zero and should take tolerances roughly on the order of the floating point precision and the second should take tolerances roughly on the order of the square root of the floating point precision. I'll be conservative with the tests and mostly use the latter macro and forgiving tolerances.

**Comment by MendocinoWhiteDeer** [comment]
This time I think the tests should work cross-platform. A relative error of 1e-6 for floats and 1e-12 for doubles should be lenient enough to account for the error. Like before, all the tests were passed on my system. The vast majority of the checks are for relative error, not absolute error.

**Comment by lerno** [comment]
Yes, all good now!

**Pull request merged**
