### PR TITLE
lib/std/collections: add Bitmap

### PR DESCRIPTION
**Pull request by pierrec**

### CODE REVIEW

**Comment by lerno** [comment]
"Bitmap" seems like a bad name. Isn't this a packed bool list? Bitmap is a name intimately associated with graphics.

**Comment by pierrec** [comment]
True, it is used in different context. Need to come up with something else.

**Comment by lerno** [comment]
BitList, BoolPack, PackedBoolList, BoolList

**Comment by lerno** [comment]
Looking at other implementations, BitSet is usually fixed size, so I propose:
BitSet - fixed size
GrowableBitSet - current implementation (or DynamicBitSet or BitList)

**Comment by lerno** [comment]
Thank you

**Pull request merged**
