### PR TITLE
Fix foreach(_r) for vectors

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by data-man** [comment]
Simple test:

```rust
import std::io;

fn void main()
{
    float[<3>] foo = { 2, 4.5, 8 };
    io::printfln("foo == %s", foo);

    foreach (float* &a : foo)
    {
        *a *= 2;
    }

    io::printfln("foo * 2 == %s", foo);

    foreach (i, float* &a : foo)
    {
        *a = i;
    }

    io::printfln("foo == %s", foo);

    foreach_r (i, float* &a : foo)
    {
        *a = i;
    }

    io::printfln("foo == %s", foo);
}
```

```
foo == [<2.000000, 4.500000, 8.000000>]
foo * 2 == [<4.000000, 9.000000, 16.000000>]
foo == [<0.000000, 1.000000, 2.000000>]
foo == [<0.000000, 1.000000, 2.000000>]
```

**Comment by lerno** [comment]
Can you prune the IR you're checking against a bit? Currently some tests are not passing due to that.

**Comment by data-man** [comment]
Yay!

**Comment by lerno** [comment]
Nice!

**Pull request merged**
