### PR TITLE
Adapt Docker script and Dockerfile

### LINKED ISSUE #1096: Docker compilation fails due to lack of release file (Fixable)
Running `./build_with_docker.sh` results in the following error when UBUNTU_VERSION is 20.10:
```
Select Build Type: Debug/Release: Release
STEP 1/7: FROM ubuntu:22.10
STEP 2/7: ARG DEPS
--> Using cache 2d33c60390984c9f50796c50647e7efd9da61457a2160dcd8689a58f2488a2bd
--> 2d33c6039098
STEP 3/7: RUN export DEBIAN_FRONTEND=noninteractive && export TERM=xterm && apt-get update && apt-get install -y build-essential cmake zlib1g zlib1g-dev          $DEPS && 	rm -rf /var/lib/apt/lists/*
Ign:1 http://security.ubuntu.com/ubuntu kinetic-security InRelease
Ign:2 http://archive.ubuntu.com/ubuntu kinetic InRelease
Ign:3 http://archive.ubuntu.com/ubuntu kinetic-updates InRelease
Err:4 http://security.ubuntu.com/ubuntu kinetic-security Release
  404  Not Found [IP: 185.125.190.39 80]
Ign:5 http://archive.ubuntu.com/ubuntu kinetic-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu kinetic Release
  404  Not Found [IP: 91.189.91.82 80]
Err:7 http://archive.ubuntu.com/ubuntu kinetic-updates Release
  404  Not Found [IP: 91.189.91.82 80]
Err:8 http://archive.ubuntu.com/ubuntu kinetic-backports Release
  404  Not Found [IP: 91.189.91.82 80]
Reading package lists...
E: The repository 'http://security.ubuntu.com/ubuntu kinetic-security Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu kinetic Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu kinetic-updates Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu kinetic-backports Release' does not have a Release file.
Error: building at STEP "RUN export DEBIAN_FRONTEND=noninteractive && export TERM=xterm && apt-get update && apt-get install -y build-essential cmake zlib1g zlib1g-dev          $DEPS && 	rm -rf /var/lib/apt/lists/*": while running runtime: exit status 100
```

This can however be fixed by rolling back the Ubuntu version slightly back to the newest LTS release (20.04). Setting `UBUNTU_VERSION="20.04"` in the script fixed the problem.

### PR DESCRIPTION
**Pull request by tclesius**
I have rewritten the `build-with-docker.sh` script and `Dockerfile`, as both are currently in a broken state. 
I made some changes to the variables in the `Dockerfile`, so the documentation will need to be updated if these changes are merged. I could take care of that. :)

The Dockerfile is heavily inspired by the gh actions CI. 

Please let me know if there any issues with these changes.

closes #1096

### CODE REVIEW

**Comment by lerno** [comment]
Now we have two different pull request, with this one #1270 

How do they relate to each other? #1270 also adds the docker file to the CI for checking, although it's not quite successful yet.

**Comment by tclesius** [comment]
Hi youre right i didnt see that! Just pulled #1270 and tried it. Saidly i get some permission errors when trying to build.

**Comment by tclesius** [comment]
I can merge the CI changes from #1270 and try to make this work since the Dockerfile and build script do differ a bit.

**Comment by lerno** [comment]
Please see if that can be done.

**Comment by tclesius** [comment]
I think this should do it :) Do you want me to remove the other linux build jobs since theire redundant now?

**Comment by lerno** [comment]
All right, I'll merge this and ask on #1270 if it can be closed.

**Pull request merged**
