### PR TITLE
encoding: implement RFC4648 base32 encoding

### PR DESCRIPTION
**Pull request by konimarti**
Implement base32 encoding and decoding according to RFC 4648 with the standard and extended hex alphabets. Add unit tests.

Link: https://www.rfc-editor.org/rfc/rfc4648

### CODE REVIEW

**Comment by lerno** [comment]
Looks good, can you also put a not in the release notes for it, plus change to Allman brace style, which is the style used in the stdlib elsewhere, so rather than this:
```c
 	if (self.padding >= 0) {
 		// with padding
 		return (n / 8) * 5;
 	} else {
 		// no padding
 		usz trailing = n % 8;
 		return n / 8 * 5 + (trailing * 5 ) / 8;
 	}
```
Use:
```c
 	if (self.padding >= 0) 
 	{
 		// with padding
 		return (n / 8) * 5;
 	} 
 	else 
 	{
 		// no padding
 		usz trailing = n % 8;
 		return n / 8 * 5 + (trailing * 5 ) / 8;
 	}
```

**Comment by konimarti** [comment]
Thanks @lerno! I've addressed your comments above with two fixup commits for easier review. Let me know if you want me to squash them.

**Comment by lerno** [comment]
I can squash it, so that's fine. Thank you for the contribution!

**Comment by lerno** [comment]
One thing that would be nice would be to have Base64 and Base32 streams. It would be a much nicer interface to output things.

**Comment by lerno** [comment]
Yeah, it's not super hard to, and you get some nice features to copy one stream to another.

**Pull request merged**
