### PR TITLE
Added print-input command line argument

### PR DESCRIPTION
**Pull request by Wrimo**
Ads command line argument print-input to print all files used for compilation. 

Resolves issue #940

### CODE REVIEW

**Comment by lerno** [comment]
I think the path is probably more correct than the name, as an example, the standard library has at least two "files.c3", but in different directories.

**Comment by lerno** [comment]
Also, you should add the feature to the release notes for 0.5.6

**Comment by Wrimo** [comment]
Alright, I've just made those changes.

**Comment by lerno** [comment]
This looks good! Thank you.

**Pull request merged**
