### PR TITLE
Add `$$memmove` built-in.

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by lerno** [comment]
Hmm.. tests do not pass?

**Comment by data-man** [comment]
Yes, there are very strange results for me. :(

**Comment by data-man** [comment]
Ah! In LLVM < 15 `memmove` hasn't alignments params.

**Comment by data-man** [comment]
No, I don't know LLVM enough to do that yet.

**Comment by lerno** [comment]
I fixed the problem (it was in memset!) and also the tests and merged it.

**Comment by data-man** [comment]
Thank you!

**Pull request closed without merging**
