### PR TITLE
Linking with LLVM Polly

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by data-man** [comment]
It's for #384.

**Comment by lerno** [comment]
So basically here, while it's interesting to pull in polly, there are no uses of it in the source code. I haven't looked, but I'm unsure if it even has a C API, so wrappers would need to be written and so on, not to mention the pain it is to get *any* extension to LLVM to work on all platforms. Just including lld has been quite a headache. It's great that you've done this work, but it has to be put on the back burner until it can be integrated, because of the maintenance issue.

**Comment by data-man** [comment]
> I haven't looked, but I'm unsure if it even has a C API

`clang` can use `Polly` with `-mllvm -polly` switch, so something like this approach can be used in c3c.

**Comment by lerno** [comment]
I will reject this for now. When we integrate Polly for real we can add the dependencies.

**Pull request closed without merging**
